
export {default as Button} from './Button'
export {default as Header} from './Header/header'
export {default as Footer} from './Footer/footer'
export {default as Content} from './Content/content'
export {default as Lab_list} from './My_lab/Lab_list/Lab_list'
export {default as Lab_2} from './My_lab/Lab_2'
export {default as Home} from './Home'
export {default as Menu} from './Menu/menu'
export {default as GetList} from './My_lab/Lab_6'
